### ISSUE TITLE
Streamlit config issue 

### ISSUE THREAD

**Issue by Denis-hamon** [Skyvern-AI/skyvern#312]
<img width="1563" alt="Capture d’écran 2024-05-14 à 09 08 17" src="https://github.com/Skyvern-AI/skyvern/assets/19908670/4e07885c-18c1-491c-992b-7f3b7202a759">
Got this issue when I launch the app on _**xxxx:8501**_

**Comment by tedramert** [comment]
Same, here @Denis-hamon. Were you able to fix this?

**Comment by LawyZheng** [comment]
Can you describe how you set up Skyvern step by step in detail?
We can't get any useful information just from the error.

**Comment by suchintan** [comment]
@Denis-hamon / @tedramert Did you run it through Docker or local setup?

**Comment by tedramert** [comment]
@suchintan these steps resulted in error for me

![Screenshot 2024-05-15 at 10 19 04 PM](https://github.com/Skyvern-AI/skyvern/assets/117756992/702bb831-6166-4e7d-a2d7-be0e50668028)

I set up my env as a contributor after 30 minutes of messing with docker configs to no avail

**Comment by Denis-hamon** [comment]
> @Denis-hamon / @tedramert Did you run it through Docker or local setup?

With latest version of Docker CE.  
As @tedramert, I follow documentation step with docker compose setup.

**Comment by suchintan** [comment]
@Denis-hamon  / @tedramert  This is really bizarre. The most common reason the streamlit file fails to create is when 
```
CMD [ "/bin/bash", "/app/entrypoint-skyvern.sh" ]
``` 

Within the Dockerfile fails to execute.

**Comment by suchintan** [comment]
Do you have multiple instances of postgres running? What's the output of `docker ps`? What about `psql -l`?

**Comment by Denis-hamon** [comment]
Docker ps gives me that : 

| CONTAINER ID | IMAGE                                    | COMMAND                  | CREATED    | STATUS              | PORTS                                       | NAMES               |
|--------------|------------------------------------------|---------------------------|------------|---------------------|----------------------------------------------|----------------------|
| 752a60b71a75 | public.ecr.aws/t6d4b5t4/skyvern:latest   | "/bin/bash entrypoin…"   | 5 days ago | Up 5 days           | 0.0.0.0:8501->8501/tcp, :::8501->8501/tcp   | skyvern-streamlit-1 |
| be449fcf9f05 | public.ecr.aws/t6d4b5t4/skyvern:latest   | "/bin/bash /app/entr…"   | 5 days ago | Up 2 seconds        |                                              | skyvern-skyvern-1   |
| d500bc008a2f | postgres:14-alpine                       | "docker-entrypoint.s…"   | 5 days ago | Up 5 days (healthy) | 5432/tcp                                    | skyvern-postgres-1  |



Error seems to be there when I type **psql -l**
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "ubuntu" does not exist

**Comment by Denis-hamon** [comment]
@suchintan 
I ve created a role on postgre and now got this when I type **psql -l**
|   Name   |  Owner  | Encoding | Collate | Ctype  | ICU Locale | Locale Provider | Access privileges     |
|----------|---------|----------|---------|--------|------------|-----------------|------------------------|
| postgres | postgres| UTF8     | C.UTF-8 | C.UTF-8|            | libc            |                        |
| template0| postgres| UTF8     | C.UTF-8 | C.UTF-8|            | libc            | =c/postgres          + |
|          |         |          |         |        |            |                 | postgres=CTc/postgres  |
| template1| postgres| UTF8     | C.UTF-8 | C.UTF-8|            | libc            | =c/postgres          + |
|          |         |          |         |        |            |                 | postgres=CTc/postgres  |


Unfortunately I still got the same issue when I am on the front : **xxxx:8501**

**Comment by suchintan** [comment]
@Denis-hamon can you try killing all running instances of postgres and run Skyvern again? I suspect it's trying to connect to the Alpine one, not the docker one and complaining

**Comment by suchintan** [comment]
Skyverns set up script creates the role for you

**Comment by Denis-hamon** [comment]
@suchintan , still the same issue, would you please try with this last GitHub version, and update installation process on a VM with Docker ? I think there are something in the middle of the process that remains not automated 

Many thanks

**Comment by suchintan** [comment]
@Denis-hamon Thanks for the pushback here -- I just dug into this and found that our Docker image hasn't updated since April 7th 😱 

We've pushed out a million changes since then haha. 

![image](https://github.com/Skyvern-AI/skyvern/assets/3853670/a6123194-7a4e-45cb-97e9-e0d7d2282cc6)


@LawyZheng is looking into the script setup again to make sure things are running OK

**Comment by suchintan** [comment]
@Denis-hamon I just pulled the latest and it works OK now. Can you give it another try?

**Comment by Denis-hamon** [comment]
@suchintan I tried again and unfortunately, it' still the same error.

**Comment by suchintan** [comment]
Can you share your docker PS output again? @Denis-hamon

**Comment by LawyZheng** [comment]
@Denis-hamon make sure about 2 things:
1. Deleting the old Skyvern image, make sure you're going to pull the latest one.
2. Make sure your `.streamlit/secrets.yml` has been deleted before you restart the container.

**Comment by Denis-hamon** [comment]
@suchintan 
1. I created a new Virtual machine completely new with 
- OS Ubuntu 24 last update
- Docker last update 
- Python last stable version 
- Postgre last update

2. There is no `.streamlit/secrets.yml` in .streamlit directory

**Comment by suchintan** [comment]
@Denis-hamon you don't need postgres or python to run Skyvern via Docker

Two questions:
1. Are you running Docker Desktop?
2. Are you just `docker compose up -d`? Or are you also running the setup scripts

**Comment by Denis-hamon** [comment]
@suchintan 

- I have python and postgre installed on my VM , not specifically though my Docker container 
- I am running Docker engine compatible with Ubuntu 24
- I just made `docker compose up -d` , I am not executing the setup scripts mentionned like `./setup.sh` or `./run_skyvern.sh`

**Comment by suchintan** [comment]
@Denis-hamon would it be helpful if we hopped on a quick call? I'd love to rapidfire a few configurations with you. Are you free at 2:30pm EST today? Do you want to follow up over email? suchintan@skyvern.com

**Comment by Denis-hamon** [comment]
Sent :) 
Many thanks
Denis
